name: memoria
description: "MEMORIA - My Second Brain"
publish_to: 'none'
version: 1.0.0+1

environment:
  # Ensures compatibility with Dart 3.x
  sdk: ">=3.0.0 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
    
# UI & Animations
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2 # FIXED: Downgraded as suggested by the solver.
  shimmer: ^3.0.0
  lottie: ^3.1.2
  glassmorphism: ^3.0.0
  flutter_neumorphic: ^3.2.0 # Previous fix retained
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^2.0.10
  smooth_page_indicator: ^1.1.0

  # State Management
  provider: ^6.1.2
  get: ^4.6.6

# Storage & Encryption
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0 # FIXED: Downgraded to a stable Dart 3 compatible version.
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  image_cropper: ^5.0.1
  pdf: ^3.11.0
  syncfusion_flutter_pdfviewer: ^26.1.42

  # AI & ML
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.2
  google_ml_kit: ^0.20.0
  camera: ^0.11.0+2
  tflite_flutter: ^0.10.4

  # Ads & Payments
  google_mobile_ads: ^5.1.0
  razorpay_flutter: ^1.3.5
  in_app_purchase: ^3.2.3
  flutter_stripe: ^10.0.0

  # Utilities
  intl: ^0.19.0 # CORRECTED: This version ensures compatibility with Dart 3.10.3
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  flutter_local_notifications: ^17.1.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.2
  device_info_plus: ^10.0.1
  flutter_native_splash: ^2.4.0
  webview_flutter: ^4.7.0
  local_auth: ^2.3.0

  # QR & Barcode
  mobile_scanner: ^5.0.0
  barcode_scan2: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/
    - assets/ai_models/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500

    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf

flutter_native_splash:
  color: "#0D1117"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  
  # Cleaned up block to prevent 'Duplicate mapping key' error
  android_12:
    image: assets/images/splash_logo.png
    color: "#0D1117"
    
  web: false
  
  dark_mode: # Only one dark_mode block is present
    color: "#0D1117"
    image: assets/images/splash_logo.png
    
